{
 "title": "Monitor: cardano-node",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Epoch",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_epoch_int {job=\"Relay-cnode\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ekg_server_timestamp_ms / 1000 - cardano_node_metrics_nodeStartTime_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Core Health",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 9, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\", instance=\"Producer-node-exporter\"}[1m])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"Producer-node-exporter\"} / (node_memory_MemTotal_bytes{instance=\"Producer-node-exporter\"})))* 100",
     "legendFormat": "RAM"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\", instance=\"Producer-node-exporter\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\", instance=\"Producer-node-exporter\"})",
     "legendFormat": "Disk"
    }
   ]
  },
  {
   "title": "Core Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsProcessedNum_int{instance=\"Producer-cnode\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Relay Health",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 9, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\", instance=\"Relay-node-exporter\"}[1m])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"Relay-node-exporter\"} / (node_memory_MemTotal_bytes{instance=\"Relay-node-exporter\"})))* 100",
     "legendFormat": "RAM"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\", instance=\"Relay-node-exporter\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\", instance=\"Relay-node-exporter\"})",
     "legendFormat": "Disk"
    }
   ]
  },
  {
   "title": "Relay Transactions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsProcessedNum_int{instance=\"Relay-cnode\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Epoch ends",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "120-(cardano_node_metrics_slotInEpoch_int{instance=\"Producer-cnode\"}/3600)",
     "legendFormat": "{{__series.name}}"
    }
   ]
  },
  {
   "title": "Core connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_connectedPeers_int{instance=\"Producer-cnode\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Relay connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_connectedPeers_int{instance=\"Relay-cnode\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "relay local connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_connectedPeers_int{instance=\"Relay-local-cnode\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Relay local Health",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 9, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\", instance=\"Relay-local-node-exporter\"}[1m])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"Relay-node-exporter\"} / (node_memory_MemTotal_bytes{instance=\"Relay-node-exporter\"})))* 100",
     "legendFormat": "RAM"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\", instance=\"Relay-local-node-exporter\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\", instance=\"Relay-local-node-exporter\"})",
     "legendFormat": "Disk"
    }
   ]
  },
  {
   "title": "local Relay Transactions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsProcessedNum_int{instance=\"Relay-local-cnode\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Slot",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotInEpoch_int {instance=\"Producer-cnode\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Processor usage [1m avg]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 3, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\", instance=\"Producer-node-exporter\"}[1m])) * 100)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\", instance=\"Relay-local-node-exporter\"}[1m])) * 100)",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\", instance=\"Relay-node-exporter\"}[1m])) * 100)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Mempool transactions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_txsInMempool_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Key rotation [days left]",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_remainingKESPeriods_int * 1.5"
    }
   ]
  },
  {
   "title": "Chain density",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_density_real{instance=\"Producer-cnode\"} * 100",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Block",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_blockNum_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Mempool bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 3, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_mempoolBytes_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "rts_gc_current_bytes_used/(1024*1024)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 9, "x": 3, "y": 30 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total[1m])",
     "legendFormat": "{{alias}} {{device}} read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total[1m])",
     "legendFormat": "{{alias}} {{device}} write"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 11, "w": 9, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "Load" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"Producer-node-exporter\"}",
     "legendFormat": "{{alias}} - Load 1m"
    },
    {
     "expr": "node_load5{instance=\"Producer-node-exporter\"}",
     "legendFormat": "{{alias}} - Load 5m"
    },
    {
     "expr": "node_load15{instance=\"Producer-node-exporter\"}",
     "legendFormat": "{{alias}} - Load 15m"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "graph",
   "gridPos": { "h": 17, "w": 9, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "bps", "label": "transmit（-）/receive（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total[1m])*8",
     "legendFormat": "{{alias}} {{device}} receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total[1m])*8",
     "legendFormat": "{{alias}} {{device}} transmit"
    }
   ]
  }
 ]
}